TeamDiamond/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oas/', include('oas.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^student/', include('student.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from . import views

app_name = "account"

urlpatterns = [
       url(r'^home/', views.home_page, name='home_page'),
       url(r'^login/', views.user_login, name='login_url'),
       url(r'^signup/', views.user_signup, name='signup_url'),
       url(r'^logout/', views.user_logout, name='logout_url'),
       url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
       url(r'^forgot_password/', views.forgot_password, name='forgot_password'),
       url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_password, name='reset_password'),
       url(r'^prompt1/', views.prompt1, name='prompt1'),
       url(r'^prompt2/', views.prompt2, name='prompt2'),
]

oas/urls.py
from django.conf.urls import url
from . import views

app_name = 'oas'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^applicants/$', views.view_applicants, name='view_applicants'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/$', views.view_applicant_detail, name='view_applicant_detail'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/approve/$', views.approve_loan, name='approve_loan'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/reject/$', views.reject_loan, name='reject_loan'),

    url(r'^loaners/$', views.view_loaners, name='view_loaners'),
    url(r'^loaners/(?P<idnum>[0-9]{8})/$', views.view_loaner_detail, name='view_loaner_detail'),
    url(r'^loaners/export/$', views.export_loaners, name='export_loaners'),

    url(r'^payments/pending/$', views.view_payments_pending, name='pending_payments'),
    url(r'^payments/all/$', views.view_payments_all, name='all_payments'),
    url(r'^payments/(?P<pk>[0-9]+)/$', views.view_payment_detail, name='view_payment_detail'),
    url(r'^payments/(?P<pk>[0-9]+)/approve/$', views.approve_payment, name='approve_payment'),
    url(r'^payments/(?P<pk>[0-9]+)/reject/$', views.reject_payment, name='reject_payment'),
    url(r'^payments/(?P<pk>[0-9]+)/edit/$', views.edit_payment, name='edit_payment'),

    url(r'^summary/$', views.view_summary, name='view_summary'),
    url(r'^create_info/$', views.create_info, name='create_info'),
    url(r'^info/$', views.view_info, name='view_info'),
    url(r'^info/(?P<pk>[\w, -]+)$', views.edit_info, name='edit_info'),

]

student/urls.py
from django.conf.urls import url
from . import views
app_name = 'student'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.user_profile, name='profile_url'),

    url(r'^loan/application$', views.loan_create, name='loan_application'),
    url(r'^loan/status$', views.view_status, name='view_status'),

    url(r'^payment/add$', views.payment_create, name='payment-add'),
    url(r'^view_payments/$', views.payments_list, name='view_payments'),
    url(r'^view_payment_details/(?P<pk>[0-9]+)/$', views.payment_detail, name='view_payment_details'),

    url(r'^calculator/$', views.loan_calc, name='calculator'),
    url(r'^calculator/result/$', views.loan_calc, name='calculation_result'),

    url(r'^calculator/loan_projection/$', views.loan_projection, name='loan_projection'),
    url(r'^calculator/loan_projection/view$', views.loan_projection, name='projection_result'),
]

student/models.py
from django.db import models
from account.models import Student


class Payment(models.Model):
    orNum = models.CharField(max_length=20)
    amount = models.FloatField()
    date = models.DateField()
    id_number = models.ForeignKey(Student, on_delete=models.CASCADE)
    isApproved = models.BooleanField(default=False)

    def __str__(self):
        return self.orNum


class Loan(models.Model):
    id_number = models.ForeignKey(Student, on_delete=models.CASCADE)
    amount = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, default='In Process')
    balance = models.FloatField(default=0)
    term_AY = models.CharField(max_length=15)
    maturity_date = models.DateField(default='2017-01-01')
    notif_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.pk.__str__()

student/forms.py
from django import forms
from student.models import Payment, Loan
from django.core.exceptions import ValidationError


class DateInput(forms.DateInput):
    input_type = 'date'


class PaymentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['orNum'].label = 'OR Number'

    class Meta:
        model = Payment
        fields = ['orNum', 'amount', 'date']

        widgets = {
            'date': DateInput(),
        }

    def clean_amount(self):
        data = super(PaymentForm, self).clean()

        amount = data.get('amount')
        if amount <= 0:
            raise ValidationError('Amount should be more than 0!')

        return amount


class LoanForm(forms.ModelForm):

    class Meta:
        model = Loan
        fields = ['amount']

    def clean_amount(self):
        data = super(LoanForm, self).clean()

        amount = data.get('amount')
        if amount <= 0:
            raise ValidationError('Amount should  be greater than 0!')
        return amount

student/views.py
from account.models import Student
from student.models import Payment, Loan
from oas.models import Info
from django.shortcuts import render, redirect
from student.forms import PaymentForm, LoanForm
from django.utils.dateparse import parse_date
from django.contrib.auth import authenticate
from calendar import monthrange
from datetime import datetime, timedelta
import calendar
import datetime
from django.http import HttpResponse


# Check if user is authenticated
def check_user(request):
    if not request.user.is_authenticated:
        return redirect('account:login_url')
    else:
        return None


# Get current term information
def get_curr_info():
    try:
        today = datetime.date.today()
        curr_info = Info.objects.get(start_of_term__lte=today, end_of_term__gte=today)
    except Info.DoesNotExist:
        curr_info = None
    return curr_info


# Student Homepage
def index_view(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        s = Student.objects.get(user=request.user)
        return render(request, 'student/index.html', {'id': s.id_number, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# View User Profile
def user_profile(request, pk):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        student = Student.objects.get(pk=pk)
        array = ["", student.first_name, student.last_name, student.id_number, student.college, student.level,
                 student.course, student.cellphone_number, student.user.email]
        if request.method == 'POST':
            college = request.POST.get('College')
            course = request.POST.get('Course')
            cellphone_number = request.POST.get('Cellphone Number')
            current_password = request.POST.get('current_password')
            new_password1 = request.POST.get('new_password1')
            new_password2 = request.POST.get('new_password2')
            user = authenticate(username=student.user.username, password=current_password)
            if user:
                user = student.user
                student.college = college
                student.course = course
                student.cellphone_number = cellphone_number
                if new_password1 != "" and new_password1 == new_password2:
                    user.set_password(new_password1)
                elif new_password1 != new_password2:
                    array[0] = " Password Mismatch "
                    s = Student.objects.get(user=request.user)
                    return render(request, 'student/profile.html', {'array': array, 'curr_info': curr_info, 'pk': s.pk})
                user.save()
                student.save()
                return redirect('student:profile_url', pk=student.id_number)
            else:
                array[0] = " Wrong Password "
                s = Student.objects.get(user=request.user)
                return render(request, 'student/profile.html', {'array': array, 'curr_info': curr_info, 'pk': s.pk})
        else:
            s = Student.objects.get(user=request.user)
            return render(request, 'student/profile.html', {'array': array, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# View payments already made by the student
def payments_list(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        s = Student.objects.get(user=request.user)
        object_list = Payment.objects.filter(id_number=s)
        return render(request, 'student/view_payments.html', {'object_list': object_list, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# View payment details
def payment_detail(request, pk):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        s = Student.objects.get(user=request.user)
        payment = Payment.objects.get(pk=pk)
        return render(request, 'student/view_payment_details.html', {'payment': payment, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# Create a payment
def payment_create(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        try:
            # Check if student already has a loan
            s = Student.objects.get(user=request.user)
            Loan.objects.get(id_number=s)

            if request.method == 'POST':
                form = PaymentForm(request.POST)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.id_number = Student.objects.get(user=request.user)
                    temp.save()
                    return redirect('student:view_payment_details', pk=temp.pk)
                else:
                    error = "Amount is not valid!"
                    return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
            # Return blank form
            else:
                form = PaymentForm(None)
            return render(request, 'student/payment_form.html', {'form': form, 'curr_info': curr_info, 'pk': s.pk})
        except Loan.DoesNotExist:
            error = "You have not applied for a Loan yet!"
            s = Student.objects.get(user=request.user)
            return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# View status of application
def view_status(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        s = Student.objects.get(user=request.user)
        try:
            l = Loan.objects.get(id_number=s)
            return render(request, 'student/view_status.html', {'loan': l, 'curr_info': curr_info, 'pk': s.pk})
        except Loan.DoesNotExist:
            error = "You have not applied for a Loan yet!"
            return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# Create a loan application
def loan_create(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        # Check if student is logged in
        s = Student.objects.get(user=request.user)
        try:
            # Check if student has a loan for this term already
            l = Loan.objects.get(id_number=s)
            if (l.balance == 0) & (not l.status == 'In Process'):
                # Check if Loan application is open
                today = datetime.date.today()
                try:
                    current_term = Info.objects.get(start_of_term__lte=today, end_of_term__gte=today)
                    if (today < current_term.application_end) & (today > current_term.application_start):
                        if request.method == 'POST':
                            form = LoanForm(request.POST)
                            if form.is_valid():
                                form.save(commit=False)
                                temp = form
                                temp.id_number = Student.objects.get(user=request.user)
                                temp.save()
                                return redirect('student:view_status')
                    else:
                        error = "You are not allowed to apply for a loan at this point in time."
                        return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
                except Info.DoesNotExist:
                    error = "Current term applications have not been set"
                    return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
            else:
                error = "You already have a loan"
                return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})

        except Loan.DoesNotExist:
            if request.method == 'POST':
                form = LoanForm(request.POST)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.id_number = Student.objects.get(user=request.user)
                    temp.save()
                    return redirect('student:view_status')
                else:
                    error = "Amount is not valid!"
                    return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
            else:
                form = LoanForm(None)
            return render(request, 'student/loan_form.html', {'form': form, 'curr_info': curr_info, 'pk': s.pk})
    else:
        return checking


# Loan calculator
def loan_calc(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()
        if request.method == 'POST':
            s = Student.objects.get(user=request.user)

            # Get end date from input
            amount = float(request.POST.get('amount_field', None))
            if amount <= 0:
                error = "Amount must be greater than 0!"
                return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})

            price = 0
            date_str1 = request.POST.get('sdate')
            start_date = parse_date(date_str1)
            date_str2 = request.POST.get('edate')
            end_date = parse_date(date_str2)

            # Error if start date is after end date
            try:
                if start_date > end_date:
                    error = "Start date cannot be before the end date!"
                    return render(request, 'student/error.html', {'error': error, 'curr_info': curr_info, 'pk': s.pk})
            except TypeError:
                error = "You have not entered a valid date range!"

templates/student/calculate_result.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'student/student.css' %}>
    <title>Result</title>
</head>
<body>


	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>

	<div class = "MainContainer">


		<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>

			</div>
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk%}"> Account</a></h4>

			</div>
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>

        <div class="ViewContainer">
        {% if data %}
            <h1>The amount you will have to pay is: {{ data|floatformat:2 }}</h1>
        {% endif %}
        </div>
</body>
</html>

templates/student/calculator_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type = "text/css" href="{% static 'student/student.css' %}">
    <title>DLSU Student Loan Calculator</title>
</head>
<body>

	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>	
		</div>	
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>
	
	<div class = "MainContainer">


		<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>	
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>
			
			</div>			
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>
			
			</div>	
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk %}"> Account</a></h4>
			
			</div>				
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>
		
		<div class="ViewContainer">
		<h1>Calculate Loan</h1>
			<div class="CalContainer">
			<form method="POST" action="{% url 'student:calculation_result' %}">
				{% csrf_token %}
                <div style="background: linear-gradient(-90deg,  rgb(61, 143, 82),rgb(38, 91, 52));color:white;text-align:center">
                    <h2>Amount</h2>
                </div>
				<input type="number" name="amount_field" id="amount_field" required><br>
				<br>
                <div style="background: linear-gradient(-90deg,  rgb(61, 143, 82),rgb(38, 91, 52));color:white;text-align:center">
                    <h2>Start Date</h2>
                </div>
				<input type="date" name="sdate" id="sdate" placeholder="Starting Month"><br>
				<br>
                <div style="background: linear-gradient(-90deg,  rgb(61, 143, 82),rgb(38, 91, 52));color:white;text-align:center">
                    <h2>End Date</h2>
                </div>
                <input type="date" name="edate" id="edate" placeholder="Ending Month"><br>
				<br>
				<button type="submit" class="btnCal">Calculate</button>
			</form>
			</div>
		</div>
		
	</div>



</body>
</html>

templates/student/error.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'student/student.css' %}>
    <title> Error </title>
</head>
<body>



	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>

    <div class = "MainContainer">

 	<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>

			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>

			</div>
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk %}"> Account</a></h4>

			</div>
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>
        <div class="ViewContainer">
            {% if error %}
                <div class="errorMsg">
                    <h1 style="color: red">{{ error }}</h1>
                </div>
            {% endif %}
        </div>
    </div>
</body>
</html>

templates/student/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type = "text/css" href="{% static 'student/student.css' %}">
    <title>DLSU Student Loan Calculator</title>
</head>
<body>

	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>	
		</div>	
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>
	
	<div class = "MainContainer">


		<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>	
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>
			
			</div>			
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>
			
			</div>	
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk %}">Account</a></h4>
			</div>				
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>
		
		<div class="ViewContainer">
			{% if user.is_authenticated %}
			<h1>Welcome! </h1>
			{% endif %}	
		</div>
		
	</div>



</body>
</html>

templates/student/loan_projection_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type = "text/css" href="{% static 'student/student.css' %}">
    <title>DLSU Student Loan Calculator</title>
</head>
<body>

	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>	
		</div>	
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>
	
	<div class = "MainContainer">


		<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>	
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>
			
			</div>			
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>
			
			</div>	
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk %}">Account</a></h4>
			
			</div>			
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>
		
		<div class="ViewContainer">
		<h1>Project Loan</h1>
			<div class="LoanProjectionContainer">
				<form method="POST" action="{% url 'student:projection_result' %}">
					{% csrf_token %}

					<input type="date" name="edate_field" id="edate_field" placeholder="Input Date of Planned Payment"><br>
					<button type="submit" class="btnProject">Project Loan</button>

				</form>
			</div>
		</div>
		
	</div>



</body>
</html>

templates/student/view_status.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type = "text/css" href="{% static 'student/student.css' %}">
    <title>DLSU Student Loan Calculator</title>
</head>
<body>

	<div class="topContainer">
		<div class="cover">
			<span class = "title">Student</span>	
		</div>	
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>
	
	<div class = "MainContainer">


		<div class="linkContainer">
			<div class="linkBox">
			<h4><a href="{% url 'student:view_status' %}">Status of application</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:loan_application' %}">Apply for a loan</a></h4>	
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:payment-add' %}">Add Payment</a></h4>
			
			</div>
			<div class="linkBox">
			<h4><a href="{% url 'student:view_payments' %}">Payments made</a></h4>
			
			</div>			
			<div class="linkBox">
			<h4><a href="{% url 'student:calculator' %}">Calculator</a></h4>
			
			</div>	
			<div class="linkBoxbottom">
			<h4><a href="{% url 'student:profile_url' pk=pk %}">Account</a></h4>
			
			</div>			
		</div>

	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
				Start of Application
				<h4> {{ curr_info.application_start }} </h4>

				End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

				Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>


		</div>
	</div>
		
		<div class="ViewContainer">
		<h1>Loan Status</h1>
            <div class="CalContainer">
            <table>
                <tr class ="tableHeader">
                    <td><h3>Loan Date</h3></td>
                    <td><h3>Loan Amount</h3></td>
                    <td><h3>Loan Status</h3></td>
                </tr>
                <tr>
                    <td>{{ loan.date }}</td>
                    <td>{{ loan.amount }}</td>
                    <td>{{ loan.status }}</td>

            </table>
			<br>


            <h4><input type="button" class="btn-success" value="View Loan Projection" onclick="location.href = '{% url 'student:loan_projection' %}'"></h4>
            </div>
            </div>
		
	</div>



</body>
</html>