TeamDiamond/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oas/', include('oas.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^student/', include('student.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from . import views

app_name = "account"

urlpatterns = [
       url(r'^home/', views.home_page, name='home_page'),
       url(r'^login/', views.user_login, name='login_url'),
       url(r'^signup/', views.user_signup, name='signup_url'),
       url(r'^logout/', views.user_logout, name='logout_url'),
       url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
       url(r'^forgot_password/', views.forgot_password, name='forgot_password'),
       url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_password, name='reset_password'),
       url(r'^prompt1/', views.prompt1, name='prompt1'),
       url(r'^prompt2/', views.prompt2, name='prompt2'),
]

oas/urls.py
from django.conf.urls import url
from . import views

app_name = 'oas'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^applicants/$', views.view_applicants, name='view_applicants'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/$', views.view_applicant_detail, name='view_applicant_detail'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/approve/$', views.approve_loan, name='approve_loan'),
    url(r'^applicants/(?P<idnum>[0-9]{8})/reject/$', views.reject_loan, name='reject_loan'),

    url(r'^loaners/$', views.view_loaners, name='view_loaners'),
    url(r'^loaners/(?P<idnum>[0-9]{8})/$', views.view_loaner_detail, name='view_loaner_detail'),
    url(r'^loaners/export/$', views.export_loaners, name='export_loaners'),

    url(r'^payments/pending/$', views.view_payments_pending, name='pending_payments'),
    url(r'^payments/all/$', views.view_payments_all, name='all_payments'),
    url(r'^payments/(?P<pk>[0-9]+)/$', views.view_payment_detail, name='view_payment_detail'),
    url(r'^payments/(?P<pk>[0-9]+)/approve/$', views.approve_payment, name='approve_payment'),
    url(r'^payments/(?P<pk>[0-9]+)/reject/$', views.reject_payment, name='reject_payment'),
    url(r'^payments/(?P<pk>[0-9]+)/edit/$', views.edit_payment, name='edit_payment'),

    url(r'^summary/$', views.view_summary, name='view_summary'),
    url(r'^create_info/$', views.create_info, name='create_info'),
    url(r'^info/$', views.view_info, name='view_info'),
    url(r'^info/(?P<pk>[\w, -]+)$', views.edit_info, name='edit_info'),

]

oas/models.py
from django.db import models
import datetime


class Info(models.Model):
    deadline_of_payment = models.DateField(default=datetime.date.today)
    loan_total = models.FloatField(default=0.0)
    budget = models.FloatField(default=0.0)
    term_AY = models.CharField(max_length=15, default='Term 1, AY17-18')   # Term 1, AY17-18
    start_of_term = models.DateField(default=datetime.date.today)
    end_of_term = models.DateField(default=datetime.date.today)
    application_start = models.DateField(default=datetime.date.today)
    application_end = models.DateField(default=datetime.date.today)
    release_of_results = models.DateField(default=datetime.date.today)
    all_notified = models.BooleanField(default=False)

    def __str__(self):
        return self.term_AY

oas/forms.py
from django import forms
from django.core.exceptions import ValidationError
from student.models import Payment
from .models import Info
import re


class DateInput(forms.DateInput):
    input_type = 'date'


class PaymentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['orNum'].label = 'OR Number'

    class Meta:
        model = Payment
        fields = ['orNum', 'amount', 'date']

    def clean_amount(self):
        data = super(PaymentForm, self).clean()

        amount = data.get('amount')
        if amount <= 0:
            raise ValidationError('Amount should be more than 0')

        return amount


class InfoForm(forms.ModelForm):

    class Meta:
        model = Info
        fields = ['term_AY', 'budget', 'start_of_term', 'end_of_term', 'application_start',
                  'application_end', 'release_of_results', 'deadline_of_payment']
        widgets = {
            'start_of_term': DateInput(),
            'end_of_term': DateInput(),
            'application_start': DateInput(),
            'application_end': DateInput(),
            'release_of_results': DateInput(),
            'deadline_of_payment': DateInput(),
        }

    def clean_budget(self):
        data = super(InfoForm, self).clean()

        budget = data.get('budget')
        if budget <= 0:
            raise ValidationError('Budget should be more than 0')

        return budget

    def clean_term_AY(self):
        data = super(InfoForm, self).clean()

        term = data.get('term_AY')

        # check if term_AY follows the pattern
        match = re.match('^Term [123], AY[0-9][0-9]-[0-9][0-9]', term)
        if not match:
            raise ValidationError('Invalid format! Please follow: Term x, AYxx-xx')

        return term

    def clean(self):
        data = super(InfoForm, self).clean()

        application_start = data.get('application_start')
        application_end = data.get('application_end')
        end_of_term = data.get('end_of_term')
        start_of_term = data.get('start_of_term')
        deadline_of_payment = data.get('deadline_of_payment')
        release_of_results = data.get('release_of_results')

        if start_of_term >= end_of_term:
            self.add_error('end_of_term', 'End of term should be later than start of term')

        if application_start >= application_end:
            self.add_error('application_end', 'End of application should be later than start of application')

        if release_of_results >= deadline_of_payment:
            self.add_error('deadline_of_payment', 'Deadline of payment should be later than release of results')

        return data

oas/views.py
from django.shortcuts import render, redirect
from account.models import Student
from student.models import Loan, Payment
from .models import Info
from .forms import PaymentForm, InfoForm
import datetime
import csv
from django.http import HttpResponse
from dateutil.relativedelta import relativedelta
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from smtplib import SMTPException


def check_user(request):
    if not request.user.is_authenticated:
        return redirect('account:login_url')
    elif Student.objects.filter(user=request.user).count() != 0:
        return redirect('student:index')
    else:
        return None


def get_curr_info():
    try:
        today = datetime.date.today()
        curr_info = Info.objects.get(start_of_term__lte=today, end_of_term__gte=today)
    except Info.DoesNotExist:
        curr_info = None
    return curr_info


def index(request):
    checking = check_user(request)
    # if user is OAS
    if checking is None:
        today = datetime.date.today()

        if Info.objects.filter(start_of_term__gte=today).count() == 0:
            return redirect('oas:create_info')

        # check all loans if addition of 1% is needed
        loans = Loan.objects.filter(balance__gte=0)
        for x in loans:
            # check if today is later than maturity date of that loan
            if today > x.maturity_date:
                x.balance *= 1.01
                # offset the maturity date by one month
                x.maturity_date = x.maturity_date + relativedelta(months=+1)
                x.save()

        # check if emails need to be sent
        # get current term
        try:
            curr_term = Info.objects.get(start_of_term__lte=today, deadline_of_payment__gte=today)
        except Info.DoesNotExist:
            curr_term = None
        except Info.MultipleObjectsReturned:
            curr_term = None

        # if today is within the current term
        if curr_term:
            # all loaners have not yet been notified AND today is a week before deadline
            if (curr_term.all_notified is False) & (today == curr_term.deadline_of_payment + relativedelta(weeks=-1)):
                #   get all active loans for this term which have not been notified yet
                loans = Loan.objects.filter(term_AY=curr_term, balance__gt=0, notif_flag=False)
                for loan in loans:
                    # get the loaner
                    student = Student.objects.get(loan__pk=loan.pk)

                    # send a notification email
                    message = render_to_string('oas/oas_email.html', {
                        'student': student,
                        'message': 'Please pay before ' + curr_term.deadline_of_payment.strftime('%m/%d/%Y')
                                   + ' to avoid incurring extra charges. Thank you!',
                    })
                    mail_subject = 'OAS Student Loan Reminder'
                    to_email = student.user.email
                    email = EmailMessage(mail_subject, message, to=[to_email])
                    try:
                        email.send()
                    except SMTPException:
                        return HttpResponse('There\'s a problem in your connection or our server might be down')
                    except TimeoutError:
                        return HttpResponse('Timeout Error. Check your internet connection')

                    loan.notif_flag = True
                    loan.save()

                unnotified_loans = Loan.objects.filter(notif_flag=False)
                all_loans = Loan.objects.all()

                # if there are existing unnotified loans
                # (put in all loans so that if there are no loans, this will not execute)
                if (all_loans is not None) & (unnotified_loans is not None):
                    # set notif flag in current term to True
                    curr_term.all_notified = True
                    curr_term.save()

        return redirect('oas:view_summary')
    else:
        return checking


def view_applicants(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()

        applicant_list = Student.objects.filter(loan__balance=0).order_by('id_number')
        loan_list = []
        for applicant in applicant_list:
            loan_list.append(Loan.objects.get(id_number=applicant))
        zipped_data = zip(applicant_list, loan_list)
        return render(request, 'oas/applicants.html', {'data': zipped_data, 'curr_info': curr_info})
    else:
        return checking


def view_applicant_detail(request, idnum):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()

        notif = None
        student = Student.objects.get(id_number=idnum)
        loan = Loan.objects.get(id_number=student)
        return render(request, 'oas/app_details.html', {'student': student, 'loan': loan, 'notif': notif,
                                                        'curr_info': curr_info})
    else:
        return checking


def approve_loan(request, idnum):
    checking = check_user(request)
    if checking is None:
        # get current term/AY
        today = datetime.date.today()
        student = Student.objects.get(id_number=idnum)
        loan = Loan.objects.get(id_number=student)

        try:
            curr_info = Info.objects.get(start_of_term__lte=today, end_of_term__gte=today)

            # check if they'd go overbudget
            if curr_info.budget - curr_info.loan_total - loan.amount < 0:
                notif = 'If you approve this loan, you\'ll go over the term budget!\nBudget left: '\
                        + str(curr_info.budget-curr_info.loan_total)

                return render(request, 'oas/app_details.html', {'student': student, 'loan': loan, 'notif': notif,
                                                                'curr_info': curr_info})
            else:
                loan.status = 'Approved'
                loan.balance = loan.amount
                loan.term_AY = curr_info.term_AY
                # set the maturity date of loan to deadline of payments of current term
                loan.maturity_date = curr_info.deadline_of_payment + relativedelta(months=+3)
                loan.save()

                curr_info.loan_total += loan.amount
                curr_info.save()

                notif = 'Loan application has been approved!'

                # send a notification email
                message = render_to_string('oas/oas_email.html', {
                    'student': student,
                    'message': 'We are pleased to inform you that your loan application has been approved! '
                               'Please log in to your account to view the details.'
                })
                mail_subject = 'OAS Student Loan Application'
                to_email = student.user.email
                email = EmailMessage(mail_subject, message, to=[to_email])
                try:
                    email.send()
                except SMTPException:
                    return HttpResponse('There\'s a problem in your connection or our server might be down')
                except TimeoutError:
                    return HttpResponse('Timeout Error. Check your internet connection')

                return render(request, 'oas/app_details.html', {'student': student, 'loan': loan, 'notif': notif,
                                                                'curr_info': curr_info})

        except Info.DoesNotExist:
            notif = 'You cannot approve/reject loans during this time.'
            return render(request, 'oas/app_details.html', {'student': student, 'loan': loan, 'notif': notif})
    else:
        return checking


def reject_loan(request, idnum):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()

        if request.method == 'POST':
            if request.POST.get('choice') == 'Yes':
                student = Student.objects.get(pk=idnum)
                loan = Loan.objects.get(id_number=student)
                loan.status = 'Rejected'
                loan.save()
                notif = 'Loan application has been rejected.'

                # send a notification email
                message = render_to_string('oas/oas_email.html', {
                    'student': student,
                    'message': 'We are sorry to inform you that your loan application has been rejected.'
                               'Please log in to your account to reapply.'
                })
                mail_subject = 'OAS Student Loan Application'
                to_email = student.user.email
                email = EmailMessage(mail_subject, message, to=[to_email])
                try:
                    email.send()
                except SMTPException:
                    return HttpResponse('There\'s a problem in your connection or our server might be down')
                except TimeoutError:
                    return HttpResponse('Timeout Error. Check your internet connection')

                return render(request, 'oas/app_details.html', {'student': student, 'loan': loan, 'notif': notif,
                                                                'curr_info': curr_info})
            else:
                return redirect('oas:view_applicant_detail', idnum=idnum)
        else:
            student = Student.objects.get(pk=idnum)
            loan = Loan.objects.get(id_number=student)
            return render(request, 'oas/reject_loan.html', {'student': student, 'loan': loan, 'curr_info': curr_info})
    else:
        return checking


def view_loaners(request):
    checking = check_user(request)
    if checking is None:
        curr_info = get_curr_info()

        loaners = Student.objects.filter(loan__status="Approved").order_by('id_number')
        loan_list = []
        for loaner in loaners:

templates/oas/app_details.html
<!DOCTYPE html>
    {% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'oas/oas.css' %}>
    <title>{{ student.id_number }}</title>
</head>
<body>
<div class="topContainer">
		<div class="cover">
			<span class = "title">OAS</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>
 <div class = "MainContainer">

     <div class="linkContainer">
        <div class="linkBox">
    <h4><a href="{% url 'oas:view_applicants' %}">View applicants</a></h4>

        </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_loaners' %}">View loaners</a></h4>

            </div>
        	<div class="linkBox">
    <h4><a href="{% url 'oas:all_payments' %}">View payments</a></h4>

            </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_summary' %}">View term summary</a></h4>

            </div>
        	<div class="linkBoxbottom">
    <h4><a href="{% url 'oas:view_info' %}">Edit term information</a></h4>

            </div>
	</div>
	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
                Start of Application
				<h4> {{ curr_info.application_start }} </h4>

                End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

                Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>
		</div>
	</div>


<div class="ViewContainer">
		{% if notif %}
            <div class="notif">
                <h1 style="color:red">{{ notif|linebreaks }}</h1>
            </div>
		{% endif %}
    <div class="MidContainer">
    <div style="margin: 0 auto; ">
	<div class="StudentInfoContainer">

		<div class="LabelContainer">
			<h4>ID Number:</h4>
		</div>

		<div class="DataContainer">
            <br>
			<h4>{{ student.id_number }}<br></h4>

		</div>
	</div>
	
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Student Name:</h4>

		</div>

		<div class="DataContainer">
			<h4> {{ student.last_name }}, {{ student.first_name }}<br></h4>

		</div>
	</div>
	
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>College:</h4>

		</div>

		<div class="DataContainer">
			<h4> {{ student.college }}<br></h4>

		</div>
	</div>
	
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Year Level:</h4>

		</div>

		<div class="DataContainer">
			<h4>{{ student.level }}<br></h4>

		</div>
	</div>
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Course:</h4>

		</div>

		<div class="DataContainer">
			<h4>{{ student.course }}<br></h4>

		</div>
	</div>
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Email:</h4>
			
		</div>

		<div class="DataContainer">
			<h4>{{ student.user.email }}<br></h4>

		</div>
	</div>
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Cellphone Number:</h4>

		</div>

		<div class="DataContainer">
			<h4>{{ student.cellphone_number }}<br></h4>

		</div>
	</div>
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Loan Amount:</h4>
		</div>

		<div class="DataContainer">
			<h4>{{ loan.amount }}<br></h4>
		</div>
	</div>
	<div class="StudentInfoContainer">
		<div class="LabelContainer">
			<h4>Loan Status:</h4>
		</div>

		<div class="DataContainer">
			<h4>{{ loan.status }}<br></h4>
		</div>
	</div>
    </div>
	<br>
	<div class="Appcontainer">

		{% if loan.status == 'In Process' %}
			<input type="button" class="btnApp" value="Approve loan" onclick="location.href = '{% url 'oas:approve_loan' student.id_number %}'"><br><br>
			<input type="button" class="btnApp" value="Reject loan" onclick="location.href = '{% url 'oas:reject_loan' student.id_number %}'"><br><br>
		{% endif %}

		<input type="button"  class="btnApp" value="Back" onclick="location.href = '{% url 'oas:view_applicants' %}'">

		{% block modal0 %}
		{% endblock %}
	</div>
    </div>
</div>
</body>
</html>

templates/oas/applicants.html
<!DOCTYPE html>
    {% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'oas/oas.css' %}>
    <title>{% block title %}Applicants{% endblock %}</title>
</head>
<body>


	<div class="topContainer">
		<div class="cover">
			<span class = "title">OAS</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>

    <div class = "MainContainer">

     <div class="linkContainer">
        <div class="linkBox">
    <h4><a href="{% url 'oas:view_applicants' %}">View applicants</a></h4>

        </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_loaners' %}">View loaners</a></h4>

            </div>
        	<div class="linkBox">
    <h4><a href="{% url 'oas:all_payments' %}">View payments</a></h4>

            </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_summary' %}">View term summary</a></h4>

            </div>
        	<div class="linkBoxbottom">
    <h4><a href="{% url 'oas:view_info' %}">Edit term information</a></h4>

            </div>
	</div>
	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
                Start of Application
				<h4> {{ curr_info.application_start }} </h4>

                End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

                Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>
		</div>
	</div>






<div class="ViewContainer">
    {% if data %}

    <h1>Applicants</h1><br>
        <table>
            <tr class="tableHeader">
                <td>Name</td>
                <td>Loan Amount</td>
                <td>Status</td>
                <td>Date applied</td>
            </tr>
        {% for applicant, loan in data %}
            <tr>
                <td><a href="{% url 'oas:view_applicant_detail' applicant.id_number %}" style="left:0%;">{{ applicant.first_name }} {{ applicant.last_name }}</a></td></h4>
                <td>₱ {{ loan.amount }}</td>
                <td>{{ loan.status }}</td>
                <td>{{ loan.date }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h1>No loan applicants</h1>
    {% endif %}

</div>

</body>
</html>

templates/oas/loaners.html
<!DOCTYPE html>
    {% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'oas/oas.css' %}>
    <title>Loaners</title>
<div class="ViewContainer">
    {% if data %}

    <h1>Loaners</h1><br>
        <table>
            <tr class="tableHeader">
                <td>Name</td>
                <td>Loan Amount</td>
                <td>Date applied</td>
            </tr>
        {% for loaner, loan in data %}
            <tr>
                <td><a href="{% url 'oas:view_loaner_detail' loaner.id_number %}"style="left:0%;">{{ loaner.first_name }} {{ loaner.last_name }}</a></td>
                <td>₱ {{ loan.amount }}</td>
                <td>{{ loan.date }}</td>
            </tr>
        {% endfor %}

        </table>
		<div class="Appcontainer">
        <br>
			<input type="button" class="btnApp" value="Export loaner data to csv" onclick="location.href = '{% url 'oas:export_loaners' %}'">
		</div>
    {% else %}
        <h1>No loaners</h1>
    {% endif %}


</div>
</head>
<body>

	<div class="topContainer">
		<div class="cover">
			<span class = "title">OAS</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>

    <div class = "MainContainer">

    <div class="linkContainer">
        <div class="linkBox">
    <h4><a href="{% url 'oas:view_applicants' %}">View applicants</a></h4>
     
        </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_loaners' %}">View loaners</a></h4>
                
            </div>
        	<div class="linkBox">
    <h4><a href="{% url 'oas:all_payments' %}">View payments</a></h4>
                
            </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_summary' %}">View term summary</a></h4>
                
            </div>
        	<div class="linkBoxbottom">
    <h4><a href="{% url 'oas:view_info' %}">Edit term information</a></h4>
            
            </div>
	</div>
	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
                Start of Application
				<h4> {{ curr_info.application_start }} </h4>

                End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

                Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>
		</div>
	</div>



    </div>

</body>
</html>

templates/oas/payment_details.html
<!DOCTYPE html>
    {% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href={% static 'oas/oas.css' %}>
    <title>Payment Details</title>
</head>
<body>

<div class="topContainer">
		<div class="cover">
			<span class = "title">OAS</span>
		</div>
	</div>
	<div class="TitleBar">

		<input type="button" class="btnLogOut" value="LOG OUT" onclick="location.href = '{% url 'account:logout_url' %}'">
	</div>

    <div class = "MainContainer">

    <div class="linkContainer">
        <div class="linkBox">
    <h4><a href="{% url 'oas:view_applicants' %}">View applicants</a></h4>
     
        </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_loaners' %}">View loaners</a></h4>
                
            </div>
        	<div class="linkBox">
    <h4><a href="{% url 'oas:all_payments' %}">View payments</a></h4>
                
            </div>

        	<div class="linkBox">
    <h4><a href="{% url 'oas:view_summary' %}">View term summary</a></h4>

            </div>
        	<div class="linkBoxbottom">
    <h4><a href="{% url 'oas:view_info' %}">Edit term information</a></h4>

            </div>
	</div>
	<div class="schedContainer">
		<div class="box">
			<b> Schedule </b>
		</div>
		<div class="schedContainer2">
                <br>
                Start of Application
				<h4> {{ curr_info.application_start }} </h4>

                End of Application
				<h4> {{ curr_info.application_end }} </h4>

                Release of Results
				<h4> {{ curr_info.release_of_results }} </h4>

                Deadline of Payment
				<h4> {{ curr_info.deadline_of_payment }} </h4>
		</div>
	</div>

    
    <div class="ViewContainer" style="font-family:sans-serif;">
    {% if notif %}
            <div class="notif">
                <h1>{{ notif|linebreaks }}</h1>
            </div>
    {% endif %}
    <div class="PaymentContainer" style="margin:auto">
    <div style="padding:5px;">
        <h2 style="background: linear-gradient(-90deg,  rgb(61, 143, 82),rgb(38, 91, 52));padding:10px;color:white;width:170px;">Student details:</h2>
        <b>{{ student.id_number }}</b><br><br>
    {{ student.last_name }}, {{ student.first_name }}<br><br>
    {{ student.college }}<br><br>
    {{ student.level }}<br><br>
    {{ student.course }}<br><br>
    {{ student.user.email }}<br><br>
    {{ student.cellphone_number }}<br><br>
    <p>
    Loan amount: ₱ {{ loan.amount }}<br><br>
    Balance left: ₱ {{ loan.balance }}<br>
    </p>
    </div>
    <div style="padding:5px;">
    <p>
    <h2 style="background: linear-gradient(-90deg,  rgb(61, 143, 82),rgb(38, 91, 52));padding:10px;color:white;width:170px;">Payment details:</h2>
    <h4>OR Number:</h4> {{ payment.orNum }}<br>
    <h4>Amount:</h4> ₱ {{ payment.amount }}<br>
    <h4>Date:</h4> {{ payment.date }}<br>
    <h4>Status:</h4>
    {% if payment.isApproved %}
        Approved.<br></p>
    {% else %}
        In Process.<br></p>
    {%  endif %}
    </div>
    </div>
    {% if payment.isApproved %}

    {% else %}
        <div class="Appcontainer">
        <input type="button" class="btnApp" value="Approve" onclick="location.href = '{% url 'oas:approve_payment' payment.pk %}'"><br>
        <br>
		<input type="button" class="btnApp" value="Reject" onclick="location.href = '{% url 'oas:reject_payment' payment.pk %}'"><br>
        <br>
		<input type="button" class="btnApp" value="Edit Payment Information" onclick="location.href = '{% url 'oas:edit_payment' payment.pk %}'"><br>
        </div>
    {% endif %}

        <div class="Appcontainer">
    <br><input type="button" class="btnViewAllPayments" value="View All Payments" onclick="location.href = '{% url 'oas:all_payments' %}'">
        </div>
    </div>
</body>
</html>